const { chromium } = require('playwright');

const urls = [
  'https://sanand0.github.io/tdsdata/js_table/?seed=33',
  'https://sanand0.github.io/tdsdata/js_table/?seed=34',
  'https://sanand0.github.io/tdsdata/js_table/?seed=35',
  'https://sanand0.github.io/tdsdata/js_table/?seed=36',
  'https://sanand0.github.io/tdsdata/js_table/?seed=37',
  'https://sanand0.github.io/tdsdata/js_table/?seed=38',
  'https://sanand0.github.io/tdsdata/js_table/?seed=39',
  'https://sanand0.github.io/tdsdata/js_table/?seed=40',
  'https://sanand0.github.io/tdsdata/js_table/?seed=41',
  'https://sanand0.github.io/tdsdata/js_table/?seed=42',
];

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();

  let grandTotal = 0;

  for (const url of urls) {
    await page.goto(url, { waitUntil: 'networkidle' });

    // Wait for the table to appear (it's dynamically generated by JS)
    await page.waitForSelector('table');

    // Extract all numbers from table cells
    const sum = await page.evaluate(() => {
      let total = 0;
      const cells = document.querySelectorAll('table td, table th');
      for (const cell of cells) {
        const val = parseFloat(cell.innerText.trim());
        if (!isNaN(val)) {
          total += val;
        }
      }
      return total;
    });

    console.log(`Seed URL: ${url} | Sum: ${sum}`);
    grandTotal += sum;
  }

  console.log(`\nTotal sum across all tables: ${grandTotal}`);
  await browser.close();
})();
